name: assembleRelease

on:
  workflow_call:
    inputs:
      versionCode:
        required: true
        type: string
      versionName:
        required: true
        type: string
      repoName:
        required: true
        type: string

jobs:
  assembleRelease:
    runs-on: ubuntu-latest
    env:
      ARTIFACTS: ./artifacts
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up jdk
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: set versionCode and versionName
        run: |
          echo "VERSION_CODE=${{ inputs.versionCode }}" >> $GITHUB_ENV
          echo "VERSION_NAME=${{ inputs.versionName }}.${{ inputs.versionCode }}" >> $GITHUB_ENV
          echo "REPO_NAME=${{ inputs.repoName }}" >> $GITHUB_ENV

      - name: set version
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ env.VERSION_CODE }}
          versionName: ${{ env.VERSION_NAME }}

      - name: build
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      # "app-release-unsigned.apk" -> "$REPO_NAME-${{ env.VERSION_NAME }}-release-unsigned.apk"
      #   full_path: "./app/build/outputs/apk/release/app-release-unsigned.apk"
      #   file_name: "app-release-unsigned.apk"
      #   artifact:  "${{ env.ARTIFACTS }}/MyFoo-x.x.xxx-release-unsigned.apk"
      - name: copy unsigned artifact
        run: |
          full_path=(./app/build/outputs/apk/release/*.apk)
          file_name="$(basename $full_path)"
          artifact="${{ env.ARTIFACTS }}/${file_name/#app/$REPO_NAME-${{ env.VERSION_NAME }}}"
          mkdir -p "${{ env.ARTIFACTS }}"
          cp -- "$full_path" "$artifact"

      - name: copy map files
        run: |
          cp ./app/build/outputs/mapping/release/* "${{ env.ARTIFACTS }}"

      - name: sign
        uses: ilharp/sign-android-release@v2
        with:
          releaseDir: ./app/build/outputs/apk/release/
          signingKey: ${{ secrets.SIGNING_KEY_RELEASE }}
          keyAlias: ${{ secrets.ALIAS_RELEASE }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD_RELEASE }}
          keyPassword: ${{ secrets.KEY_PASSWORD_RELEASE }}
          buildToolsVersion: 36.0.0

      # "app-release-unsigned-signed.apk" -> "$REPO_NAME-${{ env.VERSION_NAME }}-release.apk"
      - name: copy signed artifact
        run: |
          full_path=(./app/build/outputs/apk/release/*.apk)
          file_name="$(basename $full_path)"
          artifact="${{ env.ARTIFACTS }}/$REPO_NAME-${{ env.VERSION_NAME }}-release.apk"
          cp -- "$full_path" "$artifact"

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REPO_NAME }}_release_${{ env.VERSION_NAME }}
          path: ${{ env.ARTIFACTS }}/*
          retention-days: 1
