name: assembleDebug

on:
  workflow_call:
    inputs:
      # "number" (instead of "string") *might* work for "versionCode".
      versionCode:
        required: true
        type: string
      versionName:
        required: true
        type: string
      repoName:
        required: true
        type: string

jobs:
  assembleDebug:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      # https://github.com/actions/setup-java
      - name: set up jdk
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      # https://github.com/android-actions/setup-android
      # Required only when using "self-hosted".
#      - name: set up android sdk
#        uses: android-actions/setup-android@v2

      - name: set versionCode and versionName 
        run: |
          echo "VERSION_CODE=${{ inputs.versionCode }}" >> $GITHUB_ENV
          echo "VERSION_NAME=${{ inputs.versionName }}.${{ inputs.versionCode }}" >> $GITHUB_ENV
          echo "REPO_NAME=${{ inputs.repoName }}" >> $GITHUB_ENV

      # https://github.com/marketplace/actions/increment-the-version-code-of-your-project
      # https://github.com/chkfung/android-version-actions/issues/7
      - name: set version
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ env.VERSION_CODE }}
          versionName: ${{ env.VERSION_NAME }}

#      - name: set local properties
#        env:
#          API_KEY: ${{ secrets.MAPS_API_KEY }}
#          run: echo MAPS_API_KEY="$MAPS_API_KEY" >> ./local.properties

#      # https://stackoverflow.com/a/68147075/4957915
#      - name: set gradle properties
#        env:
#          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
#          run: |
#            mkdir -p ~/.gradle/
#            echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
#            echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties

      - name: build
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      # "app-debug.apk" -> "$REPO_NAME-${{ env.VERSION_NAME }}-debug.apk"
      - name: rename unsigned artifact
        id: rename_unsigned
        run: |
          full_path=(./app/build/outputs/apk/debug/*.apk)
          dir_name="$(dirname $full_path)"
          file_name="$(basename $full_path)"
          artifact="${file_name/#app/$REPO_NAME-${{ env.VERSION_NAME }}}"
          mv -- "$dir_name"/{"$file_name","$artifact"}

      # https://github.com/ilharp/sign-android-release
      # openssl base64 < signing_key.jks | tr -d '\n'       # Required for SIGNING_KEY only.
      #
      # After signing, "./app/build/outputs/apk/debug/" will contain following files.
      #   $REPO_NAME-${{ env.VERSION_NAME }}-debug-signed.apk
      #   $REPO_NAME-${{ env.VERSION_NAME }}-debug-signed.apk.idsig
      #   $REPO_NAME-${{ env.VERSION_NAME }}-debug-temp.apk
      #   $REPO_NAME-${{ env.VERSION_NAME }}-debug.apk
      #   key.jks
      #   output-metadata.json
      - name: sign
        uses: ilharp/sign-android-release@v1
        id: sign
        with:
          releaseDir: ./app/build/outputs/apk/debug/
          signingKey: ${{ secrets.SIGNING_KEY_DEBUG }}
          keyAlias: ${{ secrets.ALIAS_DEBUG }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD_DEBUG }}
          keyPassword: ${{ secrets.KEY_PASSWORD_DEBUG }}
          buildToolsVersion: 33.0.1

      # "$REPO_NAME-${{ env.VERSION_NAME }}-debug-signed.apk" ->
      # "$REPO_NAME-${{ env.VERSION_NAME }}-debug.apk"
      - name: rename signed artifact
        id: rename_signed
        run: |
          signed_file=${{ steps.sign.outputs.signedFile }}
          artifact=$(echo "$signed_file" | sed -e 's/-signed//g')
          mv -- "$signed_file" "$artifact"
  
          echo "ARTIFACT=$artifact" >> $GITHUB_OUTPUT

      # https://github.com/actions/upload-artifact
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REPO_NAME }}_${{ env.VERSION_NAME }}
          path: ${{ steps.rename_signed.outputs.ARTIFACT }}
          retention-days: 1     # Default and max is 90.
