name: release

on:
  workflow_call:
    inputs:
      repoName:
        required: true
        type: string
      tagName:
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/download-artifact
      - name: download artifact
        uses: actions/download-artifact@v5
        with:
          path: ./

      - name: set repoName and tagName
        run: |
          echo "REPO_NAME=${{ inputs.repoName }}" >> $GITHUB_ENV
          echo "TAG_NAME=${{ inputs.tagName }}" >> $GITHUB_ENV
          ls -la ./

      - name: create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.TAG_NAME }}",
              sha: context.sha
            })

      # https://github.com/marketplace/actions/create-release
      - name: release action
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_NAME }}
          artifacts: >
            ./${{ env.REPO_NAME }}_*_${{ env.TAG_NAME }}/* 
